// <auto-generated />
using Lab27George.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab27George.Migrations
{
    [DbContext(typeof(Lab27GeorgeContext))]
    [Migration("20171018072506_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab27George.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttackPower");

                    b.Property<bool>("GameMaster");

                    b.Property<int>("Health");

                    b.Property<int>("Height");

                    b.Property<string>("Title");

                    b.HasKey("PlayerID");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
